version: '2'
services:
  php:
    image: plt-php:7.2
    container_name: plt_coupon_php
    build:
      context: .
      dockerfile: php/Dockerfile
    volumes:
      - '../project:/usr/local/project'
    networks:
      - plt-coupon

  nginx:
    image: plt-nginx:1.5
    container_name: plt_coupon_nginx
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - '../project:/usr/local/project'
    networks:
      - plt-coupon

  mysql:
    image: mysql:8.0.12
    container_name: plt_coupon_mysql
    ports:
      - '3308:3306'
    env_file:
      - .env
    networks:
      - plt-coupon

  redis:
    image: redis:5.0.0
    container_name: plt_coupon_redis
    ports:
      - '6379:6379'
    volumes:
      - 'redis-data:/data'

volumes:
  redis-data:

networks:
  plt-coupon:
    driver: bridge